### ISSUE TITLE
About SDXL-Base-v1.0 performance

### ISSUE THREAD

**Issue by youngwanLEE** [tgxs002/HPSv2#18]
Hi, I'm really impressed by your work and it will be very helpful for T2I research community.

I have two questions.

1) In your [benchmark](https://github.com/tgxs002/HPSv2#the-hps-v2-benchmark), I wonder the test settings for the SDXL-Base-v0.9 peformance, e.g., inference resolution, cfg_scale, the number of steps.

2) Have you experimented SDXL-Base-v1.0 model? 

When I tried to examine the SDXL-Base-v1.0 (using [huggingface](https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/stable_diffusion_xl)), I got this:

setting: 
 - resolution: 512x512
 - #steps: 50
 -  cfg_scale: 5.0 (default in huggingface)

Model | paintings | photo | anime | concept-art | average
-- | -- | -- | -- | -- | --
SDXL-Base v1.0 | 0.2655 | 0.2618 | 0.269 | 0.264 | 0.2651

This result is not better than your SDXL-Base-v0.9. 

It will be helpful if you comment on this.

Thanks in advance :)

**Comment by tgxs002** [comment]
This result is quite weird. Have you tried visualizing the generated images? I feel the images may not be properly generated. Another possibility is that there is something wrong with how the evaluation is conducted, for example, have you checked the correspondence between images and prompts? The score also evaluates whether an image matches a given prompt, so a wrong prompt will also lead to a significantly worse score. 

SDXL-Base-v0.9 is evaluated under the default setting. 

Looking forward to your feedback. :)

**Comment by tgxs002** [comment]
Oh, I got it. SDXL should use a resolution of 1024 instead of 512. My experience is that directly changing the resolution to 512 will significantly affect the visual quality. (at least for diffusers)

**Comment by youngwanLEE** [comment]
@tgxs002 Thanks.

I got a new result similar to your reported result.

As you commented, I set the input resolution to 1024x1024.

Model | paintings | photo | anime | concept-art | average
-- | -- | -- | -- | -- | --
SDXL-Base v1.0 | 0.2750 | 0.2829 | 0.2769 | 0.2744 | 0.2773
