### ISSUE TITLE
Question about benchmark DALL-E 2 subset

### ISSUE THREAD

**Issue by yzy-thu** [tgxs002/HPSv2#25]
Hello! Thanks for your excellent work. I'm curious about how the DALL-E subset in benchmark was collected. The images in datasets are 512x512, but Bing's image creator should output 1024x1024?

huggingface dataset path: HPDv2/benchmark/benchmark_imgs/DALLE.tar.gz

**Comment by Jaeger416** [comment]
Images from DALL-E are generated by using OpenAI's API. For details you can refer to the appendix of our paper
