### ISSUE TITLE
Why jointly training a preference predictor with rating data does not help much with preference prediction?

### ISSUE THREAD

**Issue by LinB203** [tgxs002/HPSv2#5]
I wonder that Why jointly training a preference predictor with rating data does not help much with preference prediction?
Could you explain it in details?

**Comment by KeqiangSun** [comment]
Thank you for your interest in our work! We have tried jointly training an aesthetic predictor on top of the CLIP image encoder on Simulacra and AVA. The model structure is exactly the same as the official aesthetic predictor. We empirically find that the preference accuracy does not improve compared to training only on the preference data.
This may indicate that preference data and rating data characterize different aspects of the image. Preference data is annotated with pairwise comparison while rating data is not. Moreover, the rating data from AVA is not conditioned on prompts, and the Simulacra is relatively noisy as we observed, which has a domain shift from the preference data.

**Comment by LinB203** [comment]
You mean that you train a score predictor on Simulacra and AVA. But evaluated on preference data (maybe the metric is acc or others) and found no improvement. Am I right?

**Comment by LinB203** [comment]
> Thank you for your interest in our work! We have tried jointly training an aesthetic predictor on top of the CLIP image encoder on Simulacra and AVA. The model structure is exactly the same as the official aesthetic predictor. We empirically find that the preference accuracy does not improve compared to training only on the preference data. This may indicate that preference data and rating data characterize different aspects of the image. Preference data is annotated with pairwise comparison while rating data is not. Moreover, the rating data from AVA is not conditioned on prompts, and the Simulacra is relatively noisy as we observed, which has a domain shift from the preference data.

You mean that you train a score predictor on Simulacra and AVA. But evaluated on preference data (the metric is acc or others) and found no improvement. Am I right?

**Comment by tgxs002** [comment]
No, under this setting, the preference predictor is jointly trained with the score predictor. They use different heads and different data during training, and separately evaluated. They only share the image encoder.

**Comment by LinB203** [comment]
> No, under this setting, the preference predictor is jointly trained with the score predictor. They use different heads and different data during training, and separately evaluated. They only share the image encoder.

thx.
