### ISSUE TITLE
format of test.json

### ISSUE THREAD

**Issue by LinB203** [tgxs002/HPSv2#6]
About test.json:
```
[
    {
        'prompt': str,
        'image_path': list[str],
        'rank': list[int], # ranking for image at the same index in image_path
    },
    ...
]
```
I wonder know that if `image_path` is `[better_img, worse_img, same_worse_img]`, the `rank` will be `[1, 2, 2]`, am I right?

**Comment by tgxs002** [comment]
This codebase currently does not support evaluating a dataset with tie. Maybe you can take a look at the v1 repo?
